### ISSUE TITLE
Release 2.4.5

### ISSUE THREAD

**Issue by almico** [sirensolutions/siren-join#132]
The title says it all 😄

**Comment by rendel** [comment]
@ablehein , what would be the best way to track this to include it in the next sprint ?

**Comment by jccq** [comment]
my note @ablehein

i feel this should be driven by a policy that we agree e.g. we might want
to agree (Example) that we support anything from 2.X (example 2.3) and then
we automatically put in the pipeline and release minor versions e.g. 2.3.1
2.3.1 2.3.2 for example. Customers can read this policy on the FAQ and
expect that.

Or not! maybe the policy is that we release them "on demand" but at least
its stated and tehre is a "ask for a release button" (if this is what we
prefeir) . just so that its not ad hoc.  for you to decide

*Giovanni Tummarello*   Siren Solutions - CEO
T +353 91704885 | M +353 87 1272938 |
giovanni@siren.solutions | http://siren.solutions/
Unit 13 GTC, Mervue Park, Galway, Ireland
<https://www.twitter.com/jccq?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://youtube.com/c/SirenSolutionsChannel?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://www.linkedin.com/in/giovannitummarello?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>

**Comment by fabiocorneti** [comment]
We can do like any other ES plugin, when a new ES release is out we have to schedule the update immediately; it they do not break stuff it is usually quite fast to upgrade.

**Comment by fabiocorneti** [comment]
BTW, we can move the discussion to kibi-distribution.

**Comment by baronworks** [comment]
Just wondering if there was an ETA for the release of 2.4.5

**Comment by rendel** [comment]
Should be available in central soon
