### ISSUE TITLE
Percolate document with FilterJoin Query

### ISSUE THREAD

**Issue by armaignac** [sirensolutions/siren-join#74]
Hi when i try to register a query to percolate i get the error  **No query registered for [filterjoin]**

**Comment by rendel** [comment]
Yes, it is unsupported. The fitlerjoin query element is unknown by the percolator api.
It would require extending or creating our own version of the percolator, which is not in our current roadmap at the moment. 
Also, it would probably require a different join logic, as the current one will be not that efficient for the percolator use case, since you want to perform a join for one document.
